### ISSUE TITLE
FirstUI（unix）支持 iOS, Android, web吗？

### ISSUE THREAD

**Issue by feSnake** [FirstUI/FirstUI-uvue#2]
FirstUI（unix）支持 iOS, Android, web吗？

**Comment by feSnake** [comment]
还有微信小程序 可行吗

**Comment by FirstUI** [comment]
目前支持Android 和 web ，官方还未适配ios和小程序，等待适配，如果需要适配小程序、app、H5全端目前建议使用我们uniapp版本组件库（支持nvue）。

**Comment by FirstUI** [comment]
已支持iOS, Android, web
