### ISSUE TITLE
grid循环报错

### ISSUE THREAD

**Issue by ouyunwen** [FirstUI/FirstUI-uvue#4]
页面：
<fui-grid>
				<fui-grid-item v-for="(item,index) in level1Menus" :key="item.id">
					<view class="fui-grid__cell">
						<image src="/static/images/common/icon_tabbar_3x.png" class="fui-icon" mode="widthFix">
						</image>
						<text class="fui-text">{{item.title}}</text>
					</view>
				</fui-grid-item>
			</fui-grid>

类：
class Menu {
		id : string = '';
		title : string = '';
		component : string = '';
		icon : string = '';
		children : Array<UTSJSONObject> = [];
		constructor() { }
	}
data：
data() {
			return {
				level1Menus: [] as Array<Menu>,
				names: ['1', 'a', 'rr'] as Array<string>
			}
		}
运行时报错:
<img width="1791" alt="image" src="https://github.com/FirstUI/FirstUI-uvue/assets/28798698/49566325-8e94-40ad-8539-0c603d03fc3d">
用list控件没问题：
<img width="1432" alt="image" src="https://github.com/FirstUI/FirstUI-uvue/assets/28798698/554eb816-2989-44bb-a0f1-6f92b2a27949">

**Comment by FirstUI** [comment]
没有指定array具体类型，不能之接用.,不能直接使用item.id
