### ISSUE TITLE
text控件字符长度有限？

### ISSUE THREAD

**Issue by ouyunwen** [FirstUI/FirstUI-uvue#5]
<img width="1347" alt="image" src="https://github.com/FirstUI/FirstUI-uvue/assets/28798698/b24d88cf-7cfa-4446-bc94-f5013161a959">
如图，我设置了一个内容很长的二维码，扫到text里面，结果text控件里只显示到图中红框部分，后面的都没显示出来。

**Comment by ouyunwen** [comment]
不用看了，原来默认了最大长度140，文档没写。

**Comment by FirstUI** [comment]
你说的textarea组件吗，文档属性有写maxlength

**Comment by ouyunwen** [comment]
<img width="1177" alt="image" src="https://github.com/FirstUI/FirstUI-uvue/assets/28798698/9a73a157-ac41-46bf-9934-fabc5093a3ea">
是这个组件。
