### ISSUE TITLE
app横屏下组件会显示的非常大，如何将转换rpx为px？

### ISSUE THREAD

**Issue by deajax** [FirstUI/FirstUI-uvue#7]
uniapp-x推荐使用px为单位，在横屏下rpx组件会显示的非常大，如何方便的将rpx转换为px？

**Comment by FirstUI** [comment]
目前uniapp x app端还不支持 rpxCalcMaxDeviceWidth 等配置，横屏问题后续进行优化处理，后续完善后单位进行配置处理
